=== todo-piola/htdocs-sync-dwes/Ficheros/00-xml-xsd-xslt/tiendavideojuegos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <!-- Elemento raÃ­z -->
   <xs:element name="tiendas">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="tienda" maxOccurs="unbounded" minOccurs="1">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="nombre" type="xs:string"/>
                     <xs:element name="direccion" maxOccurs="unbounded" minOccurs="1">
                        <xs:complexType>
                           <xs:sequence>
                              <xs:element name="calle" type="xs:string"/>
                              <xs:element name="ciudad" type="xs:string"/>
                              <xs:element name="pais" type="xs:string"/>
                              <xs:element name="codigo_postal" type="xs:string"/>
                           </xs:sequence>
                        </xs:complexType>
                     </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>

</xs:schema>

=== todo-piola/htdocs-sync-dwes/Ficheros/00-xml-primeros-pasos/tiendavideojuegos.xml
<?xml version="1.0"?>
<tiendas
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="tiendavideojuegos.xsd">

   <tienda id="9001">
      <nombre>Pixel Games</nombre>
      <direccion>
         <calle>Avenida del Jugador 45</calle>
         <ciudad>Madrid</ciudad>
         <pais>España</pais>
         <codigo_postal>28013</codigo_postal>
      </direccion>
      <direccion>
         <calle>Calle Nivel 88</calle>
         <ciudad>Barcelona</ciudad>
         <pais>España</pais>
         <codigo_postal>08002</codigo_postal>
      </direccion>
   </tienda>

   <tienda id="9002">
      <nombre>RetroZone</nombre>
      <direccion>
         <calle>Calle Cartucho 12</calle>
         <ciudad>Valencia</ciudad>
         <pais>España</pais>
         <codigo_postal>46001</codigo_postal>
      </direccion>
      <direccion>
         <calle>Plaza del Pixel 5</calle>
         <ciudad>Sevilla</ciudad>
         <pais>España</pais>
         <codigo_postal>41001</codigo_postal>
      </direccion>
      <direccion>
         <calle>Bulevar Puntuación Alta 100</calle>
         <ciudad>Bilbao</ciudad>
         <pais>España</pais>
         <codigo_postal>48009</codigo_postal>
      </direccion>
   </tienda>
</tiendas>
